### YamlMime:ManagedReference
items:
- uid: Pillars.Core.DI.Interfaces.ISettings
  commentId: T:Pillars.Core.DI.Interfaces.ISettings
  id: ISettings
  parent: Pillars.Core.DI.Interfaces
  children: []
  langs:
  - csharp
  - vb
  name: ISettings
  nameWithType: ISettings
  fullName: Pillars.Core.DI.Interfaces.ISettings
  type: Interface
  source:
    remote:
      path: src/Server/Core/DI/Interfaces/ISettings.cs
      branch: main
      repo: https://github.com/pillars-framework/docs
    id: ISettings
    path: ../src/Server/Core/DI/Interfaces/ISettings.cs
    startLine: 2
  assemblies:
  - Pillars
  namespace: Pillars.Core.DI.Interfaces
  syntax:
    content: public interface ISettings
    content.vb: Public Interface ISettings
references:
- uid: Pillars.Core.DI.Interfaces
  commentId: N:Pillars.Core.DI.Interfaces
  href: Pillars.html
  name: Pillars.Core.DI.Interfaces
  nameWithType: Pillars.Core.DI.Interfaces
  fullName: Pillars.Core.DI.Interfaces
  spec.csharp:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Core
    name: Core
    href: Pillars.Core.html
  - name: .
  - uid: Pillars.Core.DI
    name: DI
    href: Pillars.Core.DI.html
  - name: .
  - uid: Pillars.Core.DI.Interfaces
    name: Interfaces
    href: Pillars.Core.DI.Interfaces.html
  spec.vb:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Core
    name: Core
    href: Pillars.Core.html
  - name: .
  - uid: Pillars.Core.DI
    name: DI
    href: Pillars.Core.DI.html
  - name: .
  - uid: Pillars.Core.DI.Interfaces
    name: Interfaces
    href: Pillars.Core.DI.Interfaces.html
