### YamlMime:ManagedReference
items:
- uid: Pillars.Database.Configuration
  commentId: N:Pillars.Database.Configuration
  id: Pillars.Database.Configuration
  children:
  - Pillars.Database.Configuration.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Pillars.Database.Configuration
  nameWithType: Pillars.Database.Configuration
  fullName: Pillars.Database.Configuration
  type: Namespace
  assemblies:
  - Pillars
references:
- uid: Pillars.Database.Configuration.DatabaseSettings
  commentId: T:Pillars.Database.Configuration.DatabaseSettings
  parent: Pillars.Database.Configuration
  href: Pillars.Database.Configuration.DatabaseSettings.html
  name: DatabaseSettings
  nameWithType: DatabaseSettings
  fullName: Pillars.Database.Configuration.DatabaseSettings
- uid: Pillars.Database.Configuration
  commentId: N:Pillars.Database.Configuration
  href: Pillars.html
  name: Pillars.Database.Configuration
  nameWithType: Pillars.Database.Configuration
  fullName: Pillars.Database.Configuration
  spec.csharp:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Database
    name: Database
    href: Pillars.Database.html
  - name: .
  - uid: Pillars.Database.Configuration
    name: Configuration
    href: Pillars.Database.Configuration.html
  spec.vb:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Database
    name: Database
    href: Pillars.Database.html
  - name: .
  - uid: Pillars.Database.Configuration
    name: Configuration
    href: Pillars.Database.Configuration.html
