### YamlMime:ManagedReference
items:
- uid: Pillars.Database.Configuration.DatabaseSettings
  commentId: T:Pillars.Database.Configuration.DatabaseSettings
  id: DatabaseSettings
  parent: Pillars.Database.Configuration
  children:
  - Pillars.Database.Configuration.DatabaseSettings.Database
  - Pillars.Database.Configuration.DatabaseSettings.Host
  - Pillars.Database.Configuration.DatabaseSettings.Port
  langs:
  - csharp
  - vb
  name: DatabaseSettings
  nameWithType: DatabaseSettings
  fullName: Pillars.Database.Configuration.DatabaseSettings
  type: Class
  source:
    remote:
      path: src/Server/Database/Configuration/DatabaseSettings.cs
      branch: main
      repo: https://github.com/pillars-framework/docs
    id: DatabaseSettings
    path: ../src/Server/Database/Configuration/DatabaseSettings.cs
    startLine: 2
  assemblies:
  - Pillars
  namespace: Pillars.Database.Configuration
  syntax:
    content: 'public sealed class DatabaseSettings : ISettings'
    content.vb: Public NotInheritable Class DatabaseSettings Implements ISettings
  inheritance:
  - System.Object
  implements:
  - Pillars.Core.DI.Interfaces.ISettings
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Pillars.Database.Configuration.DatabaseSettings.Database
  commentId: P:Pillars.Database.Configuration.DatabaseSettings.Database
  id: Database
  parent: Pillars.Database.Configuration.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Database
  nameWithType: DatabaseSettings.Database
  fullName: Pillars.Database.Configuration.DatabaseSettings.Database
  type: Property
  source:
    remote:
      path: src/Server/Database/Configuration/DatabaseSettings.cs
      branch: main
      repo: https://github.com/pillars-framework/docs
    id: Database
    path: ../src/Server/Database/Configuration/DatabaseSettings.cs
    startLine: 4
  assemblies:
  - Pillars
  namespace: Pillars.Database.Configuration
  syntax:
    content: public string Database { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Database As String
  overload: Pillars.Database.Configuration.DatabaseSettings.Database*
- uid: Pillars.Database.Configuration.DatabaseSettings.Host
  commentId: P:Pillars.Database.Configuration.DatabaseSettings.Host
  id: Host
  parent: Pillars.Database.Configuration.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: DatabaseSettings.Host
  fullName: Pillars.Database.Configuration.DatabaseSettings.Host
  type: Property
  source:
    remote:
      path: src/Server/Database/Configuration/DatabaseSettings.cs
      branch: main
      repo: https://github.com/pillars-framework/docs
    id: Host
    path: ../src/Server/Database/Configuration/DatabaseSettings.cs
    startLine: 5
  assemblies:
  - Pillars
  namespace: Pillars.Database.Configuration
  syntax:
    content: public string Host { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Host As String
  overload: Pillars.Database.Configuration.DatabaseSettings.Host*
- uid: Pillars.Database.Configuration.DatabaseSettings.Port
  commentId: P:Pillars.Database.Configuration.DatabaseSettings.Port
  id: Port
  parent: Pillars.Database.Configuration.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: DatabaseSettings.Port
  fullName: Pillars.Database.Configuration.DatabaseSettings.Port
  type: Property
  source:
    remote:
      path: src/Server/Database/Configuration/DatabaseSettings.cs
      branch: main
      repo: https://github.com/pillars-framework/docs
    id: Port
    path: ../src/Server/Database/Configuration/DatabaseSettings.cs
    startLine: 6
  assemblies:
  - Pillars
  namespace: Pillars.Database.Configuration
  syntax:
    content: public int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Port As Integer
  overload: Pillars.Database.Configuration.DatabaseSettings.Port*
references:
- uid: Pillars.Database.Configuration
  commentId: N:Pillars.Database.Configuration
  href: Pillars.html
  name: Pillars.Database.Configuration
  nameWithType: Pillars.Database.Configuration
  fullName: Pillars.Database.Configuration
  spec.csharp:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Database
    name: Database
    href: Pillars.Database.html
  - name: .
  - uid: Pillars.Database.Configuration
    name: Configuration
    href: Pillars.Database.Configuration.html
  spec.vb:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Database
    name: Database
    href: Pillars.Database.html
  - name: .
  - uid: Pillars.Database.Configuration
    name: Configuration
    href: Pillars.Database.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Pillars.Core.DI.Interfaces.ISettings
  commentId: T:Pillars.Core.DI.Interfaces.ISettings
  parent: Pillars.Core.DI.Interfaces
  href: Pillars.Core.DI.Interfaces.ISettings.html
  name: ISettings
  nameWithType: ISettings
  fullName: Pillars.Core.DI.Interfaces.ISettings
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Pillars.Core.DI.Interfaces
  commentId: N:Pillars.Core.DI.Interfaces
  href: Pillars.html
  name: Pillars.Core.DI.Interfaces
  nameWithType: Pillars.Core.DI.Interfaces
  fullName: Pillars.Core.DI.Interfaces
  spec.csharp:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Core
    name: Core
    href: Pillars.Core.html
  - name: .
  - uid: Pillars.Core.DI
    name: DI
    href: Pillars.Core.DI.html
  - name: .
  - uid: Pillars.Core.DI.Interfaces
    name: Interfaces
    href: Pillars.Core.DI.Interfaces.html
  spec.vb:
  - uid: Pillars
    name: Pillars
    href: Pillars.html
  - name: .
  - uid: Pillars.Core
    name: Core
    href: Pillars.Core.html
  - name: .
  - uid: Pillars.Core.DI
    name: DI
    href: Pillars.Core.DI.html
  - name: .
  - uid: Pillars.Core.DI.Interfaces
    name: Interfaces
    href: Pillars.Core.DI.Interfaces.html
- uid: Pillars.Database.Configuration.DatabaseSettings.Database*
  commentId: Overload:Pillars.Database.Configuration.DatabaseSettings.Database
  href: Pillars.Database.Configuration.DatabaseSettings.html#Pillars_Database_Configuration_DatabaseSettings_Database
  name: Database
  nameWithType: DatabaseSettings.Database
  fullName: Pillars.Database.Configuration.DatabaseSettings.Database
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Pillars.Database.Configuration.DatabaseSettings.Host*
  commentId: Overload:Pillars.Database.Configuration.DatabaseSettings.Host
  href: Pillars.Database.Configuration.DatabaseSettings.html#Pillars_Database_Configuration_DatabaseSettings_Host
  name: Host
  nameWithType: DatabaseSettings.Host
  fullName: Pillars.Database.Configuration.DatabaseSettings.Host
- uid: Pillars.Database.Configuration.DatabaseSettings.Port*
  commentId: Overload:Pillars.Database.Configuration.DatabaseSettings.Port
  href: Pillars.Database.Configuration.DatabaseSettings.html#Pillars_Database_Configuration_DatabaseSettings_Port
  name: Port
  nameWithType: DatabaseSettings.Port
  fullName: Pillars.Database.Configuration.DatabaseSettings.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
